// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLiSanPham.Data;

#nullable disable

namespace QuanLiSanPham.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250307004315_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLiSanPham.Models.DanhMuc", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_iMaDanhMuc");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("sMoTa");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("sTen");

                    b.HasKey("Id");

                    b.ToTable("danhMucs");
                });

            modelBuilder.Entity("QuanLiSanPham.Models.SanPham", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("PK_iMaSanPham");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<float>("Gia")
                        .HasColumnType("real")
                        .HasColumnName("fGia");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("sMoTa");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("sTen");

                    b.Property<int>("danhMucId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("danhMucId");

                    b.ToTable("sanPhams");
                });

            modelBuilder.Entity("QuanLiSanPham.Models.SanPham", b =>
                {
                    b.HasOne("QuanLiSanPham.Models.DanhMuc", "danhMuc")
                        .WithMany("sanPhams")
                        .HasForeignKey("danhMucId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("danhMuc");
                });

            modelBuilder.Entity("QuanLiSanPham.Models.DanhMuc", b =>
                {
                    b.Navigation("sanPhams");
                });
#pragma warning restore 612, 618
        }
    }
}
